### ISSUE TITLE
Adding mobx to the project

### ISSUE THREAD

**Issue by vadim-bigapps** [luangjokaj/react-fondue#12]
Hi,
Can you please suggest about the proper way of adding mobx support to your project ? 
We have an issue with mobx, problem using @inject decorator in components in order to inject the stores
Thank you!

**Comment by vadim-bigapps** [comment]
Hi,
The issue was solved.
The problem was related to .babelrc configuration and plugins that are related to decorators
and was solved by using the correct order:
["@babel/plugin-proposal-decorators", { "legacy": true }],
["@babel/plugin-proposal-class-properties",{ "loose": true }]

thanks!

**Comment by 12evgen** [comment]
@vadim-bigapps Could you please show how you added mobx?
some reason it does not work for me
