### ISSUE TITLE
Not working production environment

### ISSUE THREAD

**Issue by tommyjs007** [luangjokaj/react-fondue#19]
Steps to reproduce:
1) Clone the rep
2) npm install
3) npm run prod
4) Got to the browser and type localhost:8080 and will get "Cannot GET /en"

In the console I see
"Unhandled rejection Error: Cannot find module '../../build/prod-server-bundle.js'"
Basically webpack script fails, apparently due to post css

**Comment by luangjokaj** [comment]
I’m binding the port before the all the files are processed. I do this to prevent the Heroku build timeout. So you just have to wait a little longer till the build process is finished.
