### ISSUE TITLE
how to configure syntax highlighting in css files?

### ISSUE THREAD

**Issue by 12evgen** [luangjokaj/react-fondue#21]
In IDE (webstorm) css files highlight errors.
![Снимок экрана (40)](https://user-images.githubusercontent.com/25562185/60819788-07e9c900-a1c2-11e9-9e06-b830b37ccda0.png)

How can I configure everything to be displayed correctly?

**Comment by luangjokaj** [comment]
I used to use this configuration for IntelliJ: https://github.com/luangjokaj/wordpressify/blob/master/tools/IntelliJ.xml

But you should be able to solve that with a postcss plugin, I guess.
