### ISSUE TITLE
styled-components css do not load in SSR

### ISSUE THREAD

**Issue by amitava82** [luangjokaj/react-fondue#30]
Looks like the css from styled component do not get injected to html. So, if js is disabled then no css is loaded with the page. This is causing flash of content (js on) on initial page load.

Step to repo in boilerplate:
1. Install styled-components.
2. Create a simple styled component and add to view. 
3. Turn off JS in browser and load the view. Observer no css applied.
When Js is on, it'll cause flash of content but to reproduce it, you'll need fairly large project with tons of css.

I think there is webpack config missing that should inject styled-component css to head of the page. 

Another thing (in a different project), I saw `typescript-plugin-styled-components` in webpack config. If I'm not using tsx then how will it work?

**Comment by luangjokaj** [comment]
This repository is not maintained anymore. Use www.nextify.me
