### ISSUE TITLE
Hei why always direct to path /en

### ISSUE THREAD

**Issue by zanisis** [luangjokaj/react-fondue#42]
I set my route like this.

export const routes = [
	{
		exact: true,
		path:`/login`,
		page: 'Login'
	}
];

why when i browser localhost:8080 always be direct localhost:8080/en not localhost:8080/login

**Comment by luangjokaj** [comment]
It is working here. Your path needs to be inside quotes: `'/login'` and the component Login has to be created in: `/Views/Login/`
