### ISSUE TITLE
How to do async calls?

### ISSUE THREAD

**Issue by OmranAbazid** [luangjokaj/react-fondue#5]
Is there a way to handle async requests and if yes how?

**Comment by luangjokaj** [comment]
@OmranAbazid I just pushed 4c65148. Now you should be able to use async calls.

**Comment by OmranAbazid** [comment]
Thanks for adding async await but I am asking about something else.
I am trying to fetch data from an API before loading the component so that also the server return the react component with the fetched data.

From what I understand Since you are using react universal component componentDidMount fetch will not be loaded in the server, therefore, components need to be preloaded and a static export function from the component needs to be called after that to load the data. 

I tried to read about react universal component and how to do that but most of the examples are done using redux and I do not want to use. 
Your boilerplate is perfect because it does not enforce using redux like others.

Can you please help me with doing that or provide an example of fetching data from the API inside your boilerplate.

Many thanks

**Comment by luangjokaj** [comment]
@OmranAbazid a few days ago I merged one solution for the problem you are mentioning. I tried to document how the process works: https://www.reactfondue.co/en/redux-store
I'm using Redux for this.
Let me know if this helped.
