### ISSUE TITLE
While creating dyncmic url of homepage then its gave me ------localhost:8080/undefined......

### ISSUE THREAD

**Issue by DKhateek1372** [luangjokaj/react-fondue#7]
HI, 
 
`<Route
				exact
				path="/" 
				render={routeProps => <UniversalComponent page="Home" {...routeProps} />}
			/>`

--------------

``<Route
				exact
				path="/:vendor" 
				render={routeProps => <UniversalComponent page="Home" {...routeProps} />}
			/>``

**Comment by luangjokaj** [comment]
I don't understand your point. Can you explain in details?

**Comment by Deepak2311** [comment]
I find the solution

**Comment by Deepak2311** [comment]
thanks
