### ISSUE TITLE
I am not able to write media query in views related css page....

### ISSUE THREAD

**Issue by DKhateek1372** [luangjokaj/react-fondue#8]
In global.css file media query is taken...
but you wrote media query for tag name..

Global.css file  not taking class name when i give particular css by class name....its only taken tag name....

Please gave me the solution ...

**Comment by luangjokaj** [comment]
This is not an issue.

**Comment by DKhateek1372** [comment]
NO, i wrote the css according to desktop view but it is not responive in mobile screen...

I am trying to say is that media query is not taken by view folder css files....

is there any alternate solution...

bcz the way to write media query is only for tag name....

now suppose i have 10 samg tag, for eg  <h4> at 10 places in my view ...all r at diff places....

then css will be conflict...

so to avoid conflict we need to wite css by classname.....


and classname css is not taken by ssr...


please help me...
i already finish my application...now only problem is that responsiveness.

Thanks...
